# Generated by Django 3.1.7 on 2021-02-23 15:32

from django.db import migrations
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', tasks.models.UserManager()),
            ],
        ),
    ]
